---
# Reference:
# * https://manpages.debian.org/trixie/systemd/journald.conf.5.en.html

- name: 'Set journald limits'
  notify: 'Handlers | restarted journald'
  ansible.builtin.template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
