---
- name: 'Set journald limits'
  ansible.builtin.template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Handlers | restarted journald'
