---
###############################################################################
# Journald Handlers
###############################################################################
# Journald streams are uninterrupted during restart.

- name: 'Handlers | journald'
  ansible.builtin.systemd:
    name: 'systemd-journald'
    state: 'restarted'
