---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Verify | config | assert journald active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"systemd-journald.service" in ansible_facts.services'
        fail_msg: '✘ systemd-journald service should be enabled.'

    - name: 'Verify | /etc/systemd/journald.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/systemd/journald.conf'
        test_src: 'files/journald.conf'
        test_file: '/etc/systemd/journald.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
